CREATE TABLE IF NOT EXISTS `foreign_key` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `data_source_id` bigint(20) unsigned NOT NULL COMMENT '数据源ID',
    `database_name` varchar(128) DEFAULT NULL COMMENT '数据库名',
    `schema_name` varchar(128) DEFAULT NULL COMMENT '模式名',
    `table_name` varchar(128) NOT NULL COMMENT '当前表名',
    `column_name` varchar(128) NOT NULL COMMENT '当前列名',
    `fk_name` varchar(256) DEFAULT NULL COMMENT '外键名称',
    `referenced_table` varchar(128) NOT NULL COMMENT '引用表名',
    `referenced_column` varchar(128) NOT NULL COMMENT '引用列名',
    `referenced_schema` varchar(128) DEFAULT NULL COMMENT '引用模式名',
    `referenced_database` varchar(128) DEFAULT NULL COMMENT '引用数据库名',
    `update_rule` int DEFAULT NULL COMMENT '更新规则',
    `delete_rule` int DEFAULT NULL COMMENT '删除规则',
    `comment` varchar(512) DEFAULT NULL COMMENT '备注',
    `sync_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '同步时间',
    `sync_version` varchar(64) DEFAULT NULL COMMENT '同步版本号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_fk` (`data_source_id`,`database_name`,`schema_name`,`table_name`,`column_name`,`referenced_table`,`referenced_column`),
    INDEX `idx_fk_data_source` (`data_source_id`),
    INDEX `idx_fk_referenced` (`data_source_id`,`referenced_table`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='真实外键存储表';

CREATE TABLE IF NOT EXISTS `virtual_foreign_key` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `data_source_id` bigint(20) unsigned NOT NULL COMMENT '数据源ID',
    `database_name` varchar(128) DEFAULT NULL COMMENT '数据库名',
    `schema_name` varchar(128) DEFAULT NULL COMMENT '模式名',
    `table_name` varchar(128) NOT NULL COMMENT '当前表名',
    `column_name` varchar(128) NOT NULL COMMENT '当前列名',
    `vk_name` varchar(256) DEFAULT NULL COMMENT '虚拟外键名称',
    `referenced_table` varchar(128) NOT NULL COMMENT '引用表名',
    `referenced_column` varchar(128) NOT NULL COMMENT '引用列名',
    `comment` varchar(512) DEFAULT NULL COMMENT '用户备注',
    `source_type` varchar(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源: MANUAL/INFERRED',
    `user_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '创建用户ID',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_vk` (`data_source_id`,`database_name`,`schema_name`,`table_name`,`column_name`,`referenced_table`),
    INDEX `idx_vk_data_source` (`data_source_id`),
    INDEX `idx_vk_user_source` (`user_id`,`data_source_id`,`source_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='虚拟外键存储表';
